const GALLERY_THUMB_WIDTH_PX = 250;
const GALLERY_GRID_ROW_UNIT_PX = 10;
const GALLERY_PREVIEW_COUNT = 6;

module.exports = {
  GALLERY_THUMB_WIDTH_PX,
  GALLERY_GRID_ROW_UNIT_PX,
  GALLERY_PREVIEW_COUNT,
};
